### ISSUE TITLE
Flobynoid: it is not possible to clear the first level

### ISSUE THREAD

**Issue by cybernesto** [a2-4am/4cade#484]
Flobynoid on Total Replay 5.0-alpha.3 does not change levels after destroying all bricks in tableau 000. The floppy version totalizes the score and jumps to tableau 001 "facile".

**Comment by peterferrie** [comment]
fixed in 99d85a74a53953760d431691cbb9aa36bff7e551

**Comment by cybernesto** [comment]
Tested with v.5.0 alpha 4 on a II+ clone and the issue persists. Lost balls do not cost a life, so the counter stays at 5 and the level cannot be cleared.

**Comment by peterferrie** [comment]
I suspect two separate issues - I probably accidently enabled cheats
always (counter), and perhaps another anti-tamper (level).  I will fix
this.

**Comment by peterferrie** [comment]
Fixed in 07c46301ef33742f3f3e644ba505bdc9ad1d77f5

**Comment by cybernesto** [comment]
Can confirm that is now possible to clear levels. The game resets to the Total Replay main menu on Game Over though.

**Comment by peterferrie** [comment]
Thanks, fixed in 81b94cbb13aa78b4bdff64d107ea41587ce4106d
